# Generated by Django 5.0.2 on 2024-03-03 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('birthdays', '0003_employee_telegram_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='telegram_url',
            new_name='telegram_chat_id',
        ),
    ]
